// RU: Центральная конфигурация popup и shared-логики: настройки, storage-ключи и тексты интерфейса.
// EN: Central popup/shared config: defaults, storage keys and UI translations.
export const DEFAULT_SETTINGS = {
  autoCheckOnOpen: true,
  warnOnUntrusted: false,
  strictMode: false,
  theme: "light",
  language: "ru",
  historyRetentionDays: 30,
  compactMode: false,
  blockOnUntrusted: false,
  systemNotifyOnRisk: false,
  linkHighlightEnabled: true,
  antiScamBannerEnabled: true
};

// RU: Общие пороги для ML и fallback-эвристики во всех контекстах расширения.
// EN: Shared thresholds for ML and heuristic fallback across extension contexts.
export const MODEL_THRESHOLD = 0.7;
export const HEURISTIC_THRESHOLD = 0.6;

export const HISTORY_LIMIT = 50;
export const CUSTOM_WHITELIST_KEY = "customTrustedDomains";
export const CUSTOM_BLACKLIST_KEY = "customBlockedDomains";

export const VIEW_STATES = {
  pending: {
    theme: "pending",
    badgeKey: "status.pending.badge",
    titleKey: "status.pending.title",
    hintKey: "status.pending.hint",
    riskKey: "status.pending.risk",
    recommendationsKeys: ["status.pending.recommendations.0", "status.pending.recommendations.1"]
  },
  trusted: {
    theme: "trusted",
    badgeKey: "status.trusted.badge",
    titleKey: "status.trusted.title",
    hintKey: "status.trusted.hint.list",
    riskKey: "status.trusted.risk",
    recommendationsKeys: ["status.trusted.recommendations.0", "status.trusted.recommendations.1"]
  },
  suspicious: {
    theme: "warning",
    badgeKey: "status.suspicious.badge",
    titleKey: "status.suspicious.title",
    hintKey: "status.suspicious.hint",
    riskKey: "status.suspicious.risk",
    recommendationsKeys: [
      "status.suspicious.recommendations.0",
      "status.suspicious.recommendations.1"
    ]
  },
  phishing: {
    theme: "untrusted",
    badgeKey: "status.phishing.badge",
    titleKey: "status.phishing.title",
    hintKey: "status.phishing.hint",
    riskKey: "status.phishing.risk",
    recommendationsKeys: [
      "status.phishing.recommendations.0",
      "status.phishing.recommendations.1",
      "status.phishing.recommendations.2"
    ]
  },
  blacklisted: {
    theme: "untrusted",
    badgeKey: "status.blacklist.badge",
    titleKey: "status.blacklist.title",
    hintKey: "status.blacklist.hint",
    riskKey: "status.blacklist.risk",
    recommendationsKeys: [
      "status.blacklist.recommendations.0",
      "status.blacklist.recommendations.1"
    ]
  },
  unsupported: {
    theme: "warning",
    badgeKey: "status.unsupported.badge",
    titleKey: "status.unsupported.title",
    hintKey: "status.unsupported.hint",
    riskKey: "status.unsupported.risk",
    recommendationsKeys: [
      "status.unsupported.recommendations.0",
      "status.unsupported.recommendations.1"
    ]
  },
  error: {
    theme: "error",
    badgeKey: "status.error.badge",
    titleKey: "status.error.title",
    hintKey: "status.error.hint",
    riskKey: "status.error.risk",
    recommendationsKeys: [
      "status.error.recommendations.0",
      "status.error.recommendations.1"
    ]
  }
};

export const translations = {
  ru: {
    "main.subtitle": "Главная панель защиты",
    "actions.refresh": "Перепроверить",
    "actions.settings": "Настройки",
    "actions.history": "История проверок",
    "actions.scanAll": "Проверить всё",
    "actions.back": "Назад",
    "actions.whitelist.addQuick": "Добавить в белый список",
    "actions.blacklist.add": "Добавить в чёрный список",
    "actions.report.phishing": "Сообщить о фишинге",
    "actions.official.open": "Открыть официальный сайт {domain}",
    "blacklist.title": "Чёрный список",
    "blacklist.add": "Добавить",
    "blacklist.placeholder": "bad.com",
    "blacklist.note": "Домен будет блокироваться автоматически.",
    "blacklist.empty": "Чёрный список пуст.",
    "blacklist.status.invalid": "Введите корректный домен.",
    "blacklist.status.exists": "Домен уже в чёрном списке.",
    "blacklist.status.added": "Добавлен {domain}.",
    "blacklist.status.removed": "Удалён {domain}.",
    "status.domainLabel": "Домен",
    "status.sourceLabel": "Источник проверки",
    "status.sourceValue": "trusted.json + whitelist",
    "status.sourceValue.ml": "ML-модель",
    "status.sourceValue.heuristic": "Эвристика",
    "status.sourceValue.content": "Контент страницы",
    "status.sourceValue.list": "Белый список + trusted.json",
    "status.sourceValue.whitelist": "Белый список пользователя",
    "status.sourceValue.listMissing": "trusted.json недоступен",
    "status.sourceValue.levenshtein": "Похожесть + ML",
    "status.sourceValue.brand": "Несовпадение бренда",
    "status.sourceValue.form": "Подозрительная форма",
    "status.sourceValue.strict": "Строгий режим",
    "status.sourceValue.blacklist": "Чёрный список",
    "status.lastCheck": "Последняя проверка:",
    "status.pending.badge": "Проверяем...",
    "status.pending.title": "Анализируем активную вкладку",
    "status.pending.hint": "Сравниваем адрес с актуальным каталогом доверенных сайтов.",
    "status.pending.risk": "ожидание данных",
    "status.pending.recommendations.0": "Убедитесь, что вкладка, которую нужно проверить, активна.",
    "status.pending.recommendations.1": "Подождите пару секунд, пока завершится анализ.",
    "status.bulk.result": "Проверено вкладок: {total}, рисковых: {risk}.",
    "status.bulk.empty": "Нет вкладок для проверки.",
    "status.trusted.badge": "Легитимный сайт",
    "status.trusted.title": "Сайт безопасен",
    "status.trusted.hint": "Домен проверен и признан безопасным.",
    "status.trusted.hint.list": "Домен совпадает с {match} из trusted.json.",
    "status.trusted.hint.whitelist": "Домен совпадает с {match} в вашем белом списке.",
    "status.trusted.hint.ml": "Модель считает домен безопасным, но он не найден в доверенных списках.",
    "status.trusted.risk": "безопасно",
    "status.trusted.recommendations.0": "Всегда проверяйте адрес вручную перед вводом данных.",
    "status.trusted.recommendations.1": "Используйте менеджер паролей и двухфакторную аутентификацию.",
    "status.suspicious.badge": "Подозрительный сайт",
    "status.suspicious.title": "Требует проверки",
    "status.suspicious.hint": "Похож на {spoofTarget}. Выполняем проверку.",
    "status.suspicious.brand": "На странице упоминается {brand}, но домен другой.",
    "status.suspicious.form": "Форма отправляет данные на {host}.",
    "status.suspicious.strict": "Домен отсутствует в списке доверенных.",
    "status.suspicious.unlisted": "Домен отсутствует в доверенных списках.",
    "status.suspicious.listMissing": "trusted.json недоступен, проверьте домен вручную.",
    "content.reason.password": "Форма содержит поле пароля.",
    "content.reason.otp": "Запрашивается одноразовый код.",
    "content.reason.card": "Форма запрашивает данные карты.",
    "content.reason.hiddenInputs": "На странице много скрытых полей.",
    "content.reason.login": "Страница запрашивает вход или подтверждение.",
    "content.reason.payment": "Запрошены данные оплаты.",
    "content.reason.urgent": "Есть признаки срочного требования.",
    "content.reason.externalForm": "Форма отправляет данные на другой домен.",
    "content.reason.insecureForm": "Форма отправляет данные по HTTP.",
    "content.reason.ipForm": "Форма отправляет данные на IP-адрес.",
    "content.reason.freeHost": "Сайт размещён на публичном хостинге.",
    "content.reason.brandMention": "На странице упоминается известный бренд.",
    "status.suspicious.risk": "требует проверки",
    "status.suspicious.recommendations.0": "Не вводите данные, пока не убедитесь в подлинности.",
    "status.suspicious.recommendations.1": "Проверьте адрес и сравните с официальным доменом.",
    "status.phishing.badge": "Опасный сайт",
    "status.phishing.title": "Сайт {domain} опасен",
    "status.phishing.hint": "Обнаружены признаки фишинга. Данные и загрузки блокируются.",
    "status.phishing.risk": "опасно",
    "status.phishing.recommendations.0": "Не вводите личные данные.",
    "status.phishing.recommendations.1": "Закройте страницу или вернитесь назад.",
    "status.phishing.recommendations.2": "Добавьте домен в чёрный список, если нужно.",
    "status.blacklist.badge": "В чёрном списке",
    "status.blacklist.title": "Сайт {domain} заблокирован",
    "status.blacklist.hint": "Домен добавлен в ваш чёрный список.",
    "status.blacklist.risk": "заблокирован",
    "status.blacklist.recommendations.0": "Уберите домен из ЧС в настройках, если доверяете ему.",
    "status.blacklist.recommendations.1": "Не вводите данные на этой странице.",
    "status.ml.unavailable": "ML недоступна, используем только списки доверенных.",
    "status.ml.fallback": "ML недоступна, используется эвристика.",
    "status.report.opened": "Открыли форму жалобы в Safe Browsing.",
    "status.report.openedCopied": "Открыли форму жалобы. Детали скопированы в буфер.",
    "status.report.failed": "Не удалось сформировать ссылку для жалобы.",
    "status.actions.title": "Быстрые действия",
    "status.actions.hint": "Для рискованных страниц сначала возвращайтесь назад или открывайте официальный домен, а уже потом меняйте списки.",
    "status.unsupported.badge": "Нельзя проверить",
    "status.unsupported.title": "Поддерживаются только сайты HTTP/HTTPS",
    "status.unsupported.hint": "Системные страницы браузера и локальные файлы пропускаются.",
    "status.unsupported.risk": "не определено",
    "status.unsupported.recommendations.0": "Перейдите на веб-сайт в браузере и повторите проверку.",
    "status.unsupported.recommendations.1": "Закройте окно и активируйте нужную вкладку.",
    "status.error.badge": "Ошибка проверки",
    "status.error.title": "Что-то пошло не так",
    "status.error.hint": "Не удалось выполнить проверку. {error}",
    "status.error.risk": "неизвестно",
    "status.error.recommendations.0": "Перезапустите расширение или обновите страницу.",
    "status.error.recommendations.1": "Убедитесь, что файл trusted.json не повреждён.",
    "analysis.title": "Анализ",
    "recommendations.title": "Рекомендации",
    "recommendations.initial": "Держите вкладку открытой, чтобы мы могли её проанализировать.",
    "recommendations.empty": "Рекомендации отсутствуют.",
    "quickActions.title": "Дополнительно",
    "footer.note": "CorgPhish проверяет только сайты по протоколам HTTP/HTTPS и работает локально.",
    "manual.title": "Проверить домен вручную",
    "manual.description": "Проверьте любой домен без перехода на сайт. Полезно для ссылок из писем или чатов.",
    "manual.action": "Проверить",
    "manual.placeholder": "example.com",
    "manual.hint.default": "Укажите домен или полный URL, например https://bank.com.",
    "manual.hint.success": "Домен {domain} проверен.",
    "manual.hint.invalid": "Введите корректный домен или URL.",
    "stats.title": "Обзор",
    "stats.trusted": "Доверенных",
    "stats.alerts": "Подозрительных",
    "stats.whitelist": "В белом списке",
    "history.title": "История проверок",
    "history.subtitle": "Последние результаты анализа",
    "history.sectionTitle": "Последние проверки",
    "history.empty": "Пока нет данных. Проверьте сайт.",
    "history.emptyFiltered": "Нет результатов для выбранного фильтра.",
    "history.clear": "Очистить",
    "history.note": "Хранится не более 50 последних проверок. Данные локальны.",
    "history.search.placeholder": "Поиск домена",
    "history.filter.all": "Все",
    "history.filter.trusted": "Доверенные",
    "history.filter.alert": "С риском",
    "history.filter.suspicious": "Подозрительные",
    "history.filter.phishing": "Фишинг",
    "history.filter.blacklisted": "Чёрный список",
    "history.badge.trusted": "Доверенный",
    "history.badge.alert": "Опасно",
    "history.source.manual": "Ручная проверка",
    "history.source.active": "Активная вкладка",
    "settings.title": "Настройки",
    "settings.subtitle": "Управляйте поведением CorgPhish",
    "settings.options": "Опции защиты",
    "settings.language.title": "Язык интерфейса",
    "settings.language.desc": "Переключайте русский и английский языки.",
    "settings.theme.title": "Тема интерфейса",
    "settings.theme.desc": "Переключайте светлый и тёмный режимы.",
    "settings.autoCheck.title": "Автопроверка при открытии",
    "settings.autoCheck.desc": "Автоматически запускать анализ при появлении попапа.",
    "settings.alerts.title": "Уведомления о рисках",
    "settings.alerts.desc": "Показывать предупреждение при подозрительном сайте.",
    "settings.linkHighlight.title": "Подсветка ссылок",
    "settings.linkHighlight.desc": "Помечать подозрительные ссылки прямо на странице.",
    "settings.antiScam.title": "Anti-scam баннеры",
    "settings.antiScam.desc": "Показывать предупреждение при признаках мошеннических сценариев на странице.",
    "settings.strict.title": "Строгий режим",
    "settings.strict.desc": "Все сайты вне списка доверенных помечаются как подозрительные.",
    "settings.block.title": "Блокировка ввода",
    "settings.block.desc": "На подозрительных сайтах запретить ввод и загрузки.",
    "settings.notify.title": "Системные уведомления",
    "settings.notify.desc": "Показывать уведомление при подозрительном сайте.",
    "settings.retention.title": "Автоочистка истории",
    "settings.retention.desc": "Ограничивайте давность записей в истории проверок.",
    "settings.retention.never": "Не очищать",
    "settings.retention.days7": "7 дней",
    "settings.retention.days30": "30 дней",
    "settings.retention.days90": "90 дней",
    "settings.tabs.options": "Опции",
    "settings.tabs.lists": "Списки",
    "settings.compact.title": "Компактный режим",
    "settings.compact.desc": "Меньше отступов и плотнее карточки.",
    "settings.status.default": "Изменения сохраняются автоматически.",
    "settings.status.saved": "Настройки сохранены.",
    "whitelist.title": "Ваш белый список",
    "whitelist.add": "Добавить",
    "whitelist.placeholder": "example.com",
    "whitelist.note": "Добавленные домены проверяются вместе с локальным списком trusted.json.",
    "whitelist.empty": "Белый список пуст.",
    "whitelist.status.invalid": "Введите корректный домен.",
    "whitelist.status.exists": "Домен уже в белом списке.",
    "whitelist.status.added": "Добавлен {domain}.",
    "whitelist.status.removed": "Удалён {domain}.",
    "alerts.untrusted": "CorgPhish предупреждает: сайт {domain} не найден в списке доверенных.",
    "errors.activeTab": "Невозможно получить ссылку активной вкладки.",
    "errors.loadTrusted": "Не удалось загрузить trusted.json.",
    "errors.invalidTrusted": "Файл trusted.json содержит неверный формат.",
    "errors.invalidDomain": "Некорректный домен или URL.",
    "errors.modelLoad": "Не удалось загрузить ML-модель."
  },
  en: {
    "main.subtitle": "Protection dashboard",
    "actions.refresh": "Rescan",
    "actions.settings": "Settings",
    "actions.history": "Scan history",
    "actions.scanAll": "Scan all tabs",
    "actions.back": "Back",
    "actions.whitelist.addQuick": "Add to whitelist",
    "actions.blacklist.add": "Add to blacklist",
    "actions.report.phishing": "Report phishing",
    "actions.official.open": "Open official site {domain}",
    "blacklist.title": "Blacklist",
    "blacklist.add": "Add",
    "blacklist.placeholder": "bad.com",
    "blacklist.note": "The domain will be blocked automatically.",
    "blacklist.empty": "Blacklist is empty.",
    "blacklist.status.invalid": "Enter a valid domain.",
    "blacklist.status.exists": "Domain is already blacklisted.",
    "blacklist.status.added": "Added {domain}.",
    "blacklist.status.removed": "Removed {domain}.",
    "status.domainLabel": "Domain",
    "status.sourceLabel": "Source",
    "status.sourceValue": "trusted.json + whitelist",
    "status.sourceValue.ml": "ML model",
    "status.sourceValue.heuristic": "Heuristic check",
    "status.sourceValue.content": "Page content",
    "status.sourceValue.list": "Whitelist + trusted.json",
    "status.sourceValue.whitelist": "User whitelist",
    "status.sourceValue.listMissing": "trusted.json unavailable",
    "status.sourceValue.levenshtein": "Similarity + ML",
    "status.sourceValue.brand": "Brand mismatch",
    "status.sourceValue.form": "Suspicious form",
    "status.sourceValue.strict": "Strict mode",
    "status.sourceValue.blacklist": "Blacklist",
    "status.lastCheck": "Last check:",
    "status.pending.badge": "Scanning...",
    "status.pending.title": "Analyzing active tab",
    "status.pending.hint": "Comparing the address against the trusted domain catalog.",
    "status.pending.risk": "waiting for data",
    "status.pending.recommendations.0": "Make sure the tab you want to check is active.",
    "status.pending.recommendations.1": "Give us a second to finish the analysis.",
    "status.bulk.result": "Scanned tabs: {total}, risky: {risk}.",
    "status.bulk.empty": "No tabs available for scanning.",
    "status.trusted.badge": "Trusted site",
    "status.trusted.title": "Site is safe",
    "status.trusted.hint": "The domain looks safe based on available signals.",
    "status.trusted.hint.list": "The domain matches {match} from trusted.json.",
    "status.trusted.hint.whitelist": "The domain matches {match} in your whitelist.",
    "status.trusted.hint.ml": "The model marks this domain as safe, but it is not in the trusted lists.",
    "status.trusted.risk": "safe",
    "status.trusted.recommendations.0": "Always double-check the address before entering data.",
    "status.trusted.recommendations.1": "Use a password manager and enable MFA.",
    "status.suspicious.badge": "Suspicious site",
    "status.suspicious.title": "Needs review",
    "status.suspicious.hint": "Similar to {spoofTarget}. Running ML check.",
    "status.suspicious.brand": "The page mentions {brand}, but the domain is different.",
    "status.suspicious.form": "The form sends data to {host}.",
    "status.suspicious.strict": "The domain is not on the trusted list.",
    "status.suspicious.unlisted": "The domain is not in the trusted lists.",
    "status.suspicious.listMissing": "trusted.json is unavailable, verify the domain manually.",
    "content.reason.password": "The form contains a password field.",
    "content.reason.otp": "One-time code is requested.",
    "content.reason.card": "The form asks for card details.",
    "content.reason.hiddenInputs": "Too many hidden inputs on the page.",
    "content.reason.login": "The page asks to sign in or confirm.",
    "content.reason.payment": "Payment details are requested.",
    "content.reason.urgent": "Urgent or threatening language detected.",
    "content.reason.externalForm": "The form submits data to another domain.",
    "content.reason.insecureForm": "The form submits data over HTTP.",
    "content.reason.ipForm": "The form submits data to an IP address.",
    "content.reason.freeHost": "The site is hosted on a public platform.",
    "content.reason.brandMention": "A known brand is mentioned on the page.",
    "status.suspicious.risk": "needs review",
    "status.suspicious.recommendations.0": "Do not enter data until the site is verified.",
    "status.suspicious.recommendations.1": "Compare the address with the official domain.",
    "status.phishing.badge": "Phishing risk",
    "status.phishing.title": "{domain} is dangerous",
    "status.phishing.hint": "Phishing signals detected. Data and downloads are blocked.",
    "status.phishing.risk": "danger",
    "status.phishing.recommendations.0": "Do not enter personal data.",
    "status.phishing.recommendations.1": "Close the page or go back.",
    "status.phishing.recommendations.2": "Add the domain to blacklist if needed.",
    "status.blacklist.badge": "Blacklisted",
    "status.blacklist.title": "{domain} is blacklisted",
    "status.blacklist.hint": "The domain is in your blacklist.",
    "status.blacklist.risk": "blocked",
    "status.blacklist.recommendations.0": "Remove it from blacklist in settings if you trust it.",
    "status.blacklist.recommendations.1": "Avoid entering data on this page.",
    "status.ml.unavailable": "ML unavailable, using trusted lists only.",
    "status.ml.fallback": "ML unavailable, using heuristic checks.",
    "status.report.opened": "Opened Safe Browsing report form.",
    "status.report.openedCopied": "Opened report form and copied details.",
    "status.report.failed": "Could not build a report URL.",
    "status.actions.title": "Quick actions",
    "status.actions.hint": "On risky pages, first go back or open the official domain, then decide whether to change your lists.",
    "status.unsupported.badge": "Cannot scan",
    "status.unsupported.title": "Only HTTP/HTTPS sites are supported",
    "status.unsupported.hint": "Browser pages and local files are skipped.",
    "status.unsupported.risk": "not defined",
    "status.unsupported.recommendations.0": "Open the desired website in the browser and try again.",
    "status.unsupported.recommendations.1": "Close the popup and activate the needed tab.",
    "status.error.badge": "Scan error",
    "status.error.title": "Something went wrong",
    "status.error.hint": "We could not finish the scan. {error}",
    "status.error.risk": "unknown",
    "status.error.recommendations.0": "Reload the extension or refresh the page.",
    "status.error.recommendations.1": "Make sure the trusted.json file is valid.",
    "analysis.title": "Analysis",
    "recommendations.title": "Recommendations",
    "recommendations.initial": "Keep the tab open so we can analyze it.",
    "recommendations.empty": "No recommendations available.",
    "quickActions.title": "Quick actions",
    "footer.note": "CorgPhish only scans HTTP/HTTPS sites and works locally.",
    "manual.title": "Check a domain manually",
    "manual.description": "Inspect any domain without visiting it. Handy for links from emails or chats.",
    "manual.action": "Check",
    "manual.placeholder": "example.com",
    "manual.hint.default": "Type a domain or full URL, e.g. https://bank.com.",
    "manual.hint.success": "Domain {domain} was inspected.",
    "manual.hint.invalid": "Enter a valid domain or URL.",
    "stats.title": "Overview",
    "stats.trusted": "Trusted",
    "stats.alerts": "Flagged",
    "stats.whitelist": "In whitelist",
    "history.title": "Scan history",
    "history.subtitle": "Latest results",
    "history.sectionTitle": "Recent scans",
    "history.empty": "No scans yet. Please run a check.",
    "history.emptyFiltered": "No results for the selected filter.",
    "history.clear": "Clear",
    "history.note": "Up to 50 scans are stored locally.",
    "history.search.placeholder": "Search domain",
    "history.filter.all": "All",
    "history.filter.trusted": "Trusted",
    "history.filter.alert": "Risky",
    "history.filter.suspicious": "Suspicious",
    "history.filter.phishing": "Phishing",
    "history.filter.blacklisted": "Blacklisted",
    "history.badge.trusted": "Trusted",
    "history.badge.alert": "Alert",
    "history.source.manual": "Manual check",
    "history.source.active": "Active tab",
    "settings.title": "Settings",
    "settings.subtitle": "Control CorgPhish behaviour",
    "settings.options": "Protection options",
    "settings.language.title": "Interface language",
    "settings.language.desc": "Switch between Russian and English.",
    "settings.theme.title": "Interface theme",
    "settings.theme.desc": "Toggle light and dark modes.",
    "settings.autoCheck.title": "Auto scan on open",
    "settings.autoCheck.desc": "Launch the analysis when the popup appears.",
    "settings.alerts.title": "Risk alerts",
    "settings.alerts.desc": "Show a warning when a suspicious site is detected.",
    "settings.linkHighlight.title": "Link highlighting",
    "settings.linkHighlight.desc": "Mark suspicious links directly on the page.",
    "settings.antiScam.title": "Anti-scam banners",
    "settings.antiScam.desc": "Show warning banner when scam-like social engineering patterns are detected.",
    "settings.strict.title": "Strict mode",
    "settings.strict.desc": "Mark every non-trusted site as suspicious.",
    "settings.block.title": "Block input",
    "settings.block.desc": "Block forms/downloads on suspicious sites.",
    "settings.notify.title": "System notifications",
    "settings.notify.desc": "Show a system notification on suspicious sites.",
    "settings.retention.title": "History cleanup",
    "settings.retention.desc": "Limit how long scan records are kept.",
    "settings.retention.never": "Never",
    "settings.retention.days7": "7 days",
    "settings.retention.days30": "30 days",
    "settings.retention.days90": "90 days",
    "settings.tabs.options": "Options",
    "settings.tabs.lists": "Lists",
    "settings.compact.title": "Compact mode",
    "settings.compact.desc": "Tighter spacing and condensed cards.",
    "settings.status.default": "Changes are saved automatically.",
    "settings.status.saved": "Settings saved.",
    "whitelist.title": "Your whitelist",
    "whitelist.add": "Add",
    "whitelist.placeholder": "example.com",
    "whitelist.note": "Added domains are checked together with trusted.json.",
    "whitelist.empty": "Whitelist is empty.",
    "whitelist.status.invalid": "Enter a valid domain.",
    "whitelist.status.exists": "The domain is already on the whitelist.",
    "whitelist.status.added": "Added {domain}.",
    "whitelist.status.removed": "Removed {domain}.",
    "alerts.untrusted": "CorgPhish warns: {domain} is not in the trusted list.",
    "errors.activeTab": "Cannot read the active tab URL.",
    "errors.loadTrusted": "Failed to load trusted.json.",
    "errors.invalidTrusted": "trusted.json has an invalid format.",
    "errors.invalidDomain": "Invalid domain or URL.",
    "errors.modelLoad": "Failed to load ML model."
  }
};
