// Конфигурация: дефолтные настройки, словари переводов и константы UI.
export const DEFAULT_SETTINGS = {
  autoCheckOnOpen: true,
  warnOnUntrusted: true,
  theme: "dark",
  language: "ru",
  historyRetentionDays: 30,
  compactMode: false,
  blockOnUntrusted: true,
  systemNotifyOnRisk: true
};

export const HISTORY_LIMIT = 50;
export const CUSTOM_WHITELIST_KEY = "customTrustedDomains";

export const VIEW_STATES = {
  pending: {
    theme: "pending",
    badgeKey: "status.pending.badge",
    titleKey: "status.pending.title",
    hintKey: "status.pending.hint",
    riskKey: "status.pending.risk",
    recommendationsKeys: ["status.pending.recommendations.0", "status.pending.recommendations.1"]
  },
  trusted: {
    theme: "trusted",
    badgeKey: "status.trusted.badge",
    titleKey: "status.trusted.title",
    hintKey: "status.trusted.hint",
    riskKey: "status.trusted.risk",
    recommendationsKeys: ["status.trusted.recommendations.0", "status.trusted.recommendations.1"]
  },
  untrusted: {
    theme: "untrusted",
    badgeKey: "status.untrusted.badge",
    titleKey: "status.untrusted.title",
    hintKey: "status.untrusted.hint",
    riskKey: "status.untrusted.risk",
    recommendationsKeys: [
      "status.untrusted.recommendations.0",
      "status.untrusted.recommendations.1",
      "status.untrusted.recommendations.2"
    ]
  },
  mlSafe: {
    theme: "trusted",
    badgeKey: "status.mlSafe.badge",
    titleKey: "status.mlSafe.title",
    hintKey: "status.mlSafe.hint",
    riskKey: "status.mlSafe.risk",
    recommendationsKeys: [
      "status.trusted.recommendations.0",
      "status.trusted.recommendations.1"
    ]
  },
  mlRisky: {
    theme: "untrusted",
    badgeKey: "status.mlRisky.badge",
    titleKey: "status.mlRisky.title",
    hintKey: "status.mlRisky.hint",
    riskKey: "status.mlRisky.risk",
    recommendationsKeys: [
      "status.untrusted.recommendations.0",
      "status.untrusted.recommendations.1",
      "status.untrusted.recommendations.2"
    ]
  },
  unsupported: {
    theme: "warning",
    badgeKey: "status.unsupported.badge",
    titleKey: "status.unsupported.title",
    hintKey: "status.unsupported.hint",
    riskKey: "status.unsupported.risk",
    recommendationsKeys: [
      "status.unsupported.recommendations.0",
      "status.unsupported.recommendations.1"
    ]
  },
  error: {
    theme: "error",
    badgeKey: "status.error.badge",
    titleKey: "status.error.title",
    hintKey: "status.error.hint",
    riskKey: "status.error.risk",
    recommendationsKeys: [
      "status.error.recommendations.0",
      "status.error.recommendations.1"
    ]
  }
};

export const translations = {
  ru: {
    "main.subtitle": "Главная панель защиты",
    "actions.refresh": "Перепроверить",
    "actions.settings": "Настройки",
    "actions.history": "История проверок",
    "actions.back": "Назад",
    "actions.whitelist.addQuick": "Добавить в белый список",
    "status.domainLabel": "Домен",
    "status.sourceLabel": "Источник проверки",
    "status.sourceValue": "trusted.json + ML + whitelist",
    "status.sourceValue.ml": "ML-модель",
    "status.sourceValue.list": "Белый список + trusted.json",
    "status.sourceValue.mlRisk": "ML-модель (высокий риск)",
    "status.lastCheck": "Последняя проверка:",
    "status.pending.badge": "Проверяем...",
    "status.pending.title": "Анализируем активную вкладку",
    "status.pending.hint": "Сравниваем адрес с актуальным каталогом доверенных сайтов.",
    "status.pending.risk": "ожидание данных",
    "status.pending.recommendations.0": "Убедитесь, что вкладка, которую нужно проверить, активна.",
    "status.pending.recommendations.1": "Подождите пару секунд, пока завершится анализ.",
    "status.trusted.badge": "Доверенный сайт",
    "status.trusted.title": "Сайт {domain} подтверждён",
    "status.trusted.hint": "Домен найден в локальном списке доверенных ресурсов.",
    "status.trusted.risk": "низкий риск",
    "status.trusted.recommendations.0": "Всегда проверяйте адрес вручную перед вводом данных.",
    "status.trusted.recommendations.1": "Используйте менеджер паролей и двухфакторную аутентификацию.",
    "status.untrusted.badge": "Подозрительный сайт",
    "status.untrusted.title": "Сайт {domain} не найден в каталоге",
    "status.untrusted.hint": "Это может быть новая площадка или потенциальный фишинг.",
    "status.untrusted.risk": "высокий риск",
    "status.untrusted.recommendations.0": "Не вводите личные данные до подтверждения подлинности сайта.",
    "status.untrusted.recommendations.1": "Сверьте адрес с официальным доменом организации.",
    "status.untrusted.recommendations.2": "Поищите отзывы и упоминания домена {domain} в открытых источниках.",
    "status.untrusted.spoofWarning": "Похоже на {spoofTarget}. Возможный спуфинг.",
    "status.mlSafe.badge": "ML: низкий риск",
    "status.mlSafe.title": "ML считает {domain} безопасным",
    "status.mlSafe.hint": "Домен не в списке, но модель оценила его как легитимный.",
    "status.mlSafe.risk": "низкий риск (ML)",
    "status.mlRisky.badge": "ML: риск",
    "status.mlRisky.title": "ML считает {domain} рискованным",
    "status.mlRisky.hint": "Домен не в списке, модель видит высокий риск фишинга.",
    "status.mlRisky.risk": "высокий риск (ML)",
    "status.unsupported.badge": "Нельзя проверить",
    "status.unsupported.title": "Поддерживаются только сайты HTTP/HTTPS",
    "status.unsupported.hint": "Системные страницы браузера и локальные файлы пропускаются.",
    "status.unsupported.risk": "не определено",
    "status.unsupported.recommendations.0": "Перейдите на веб-сайт в браузере и повторите проверку.",
    "status.unsupported.recommendations.1": "Закройте окно и активируйте нужную вкладку.",
    "status.error.badge": "Ошибка проверки",
    "status.error.title": "Что-то пошло не так",
    "status.error.hint": "Не удалось выполнить проверку. {error}",
    "status.error.risk": "неизвестно",
    "status.error.recommendations.0": "Перезапустите расширение или обновите страницу.",
    "status.error.recommendations.1": "Убедитесь, что файл trusted.json не повреждён.",
    "recommendations.title": "Рекомендации",
    "recommendations.initial": "Держите вкладку открытой, чтобы мы могли её проанализировать.",
    "recommendations.empty": "Рекомендации отсутствуют.",
    "quickActions.title": "Дополнительно",
    "footer.note": "CorgPhish проверяет только сайты по протоколам HTTP/HTTPS и работает локально.",
    "manual.title": "Проверить домен вручную",
    "manual.description": "Проверьте любой домен без перехода на сайт. Полезно для ссылок из писем или чатов.",
    "manual.action": "Проверить",
    "manual.placeholder": "example.com",
    "manual.hint.default": "Укажите домен или полный URL, например https://bank.com.",
    "manual.hint.success": "Домен {domain} проверен.",
    "manual.hint.invalid": "Введите корректный домен или URL.",
    "stats.title": "Обзор",
    "stats.trusted": "Доверенных",
    "stats.alerts": "Подозрительных",
    "stats.whitelist": "В белом списке",
    "history.title": "История проверок",
    "history.subtitle": "Последние результаты анализа",
    "history.sectionTitle": "Последние проверки",
    "history.empty": "Пока нет данных. Проверьте сайт.",
    "history.clear": "Очистить",
    "history.note": "Хранится не более 50 последних проверок. Данные локальны.",
    "history.badge.trusted": "Доверенный",
    "history.badge.alert": "Опасно",
    "history.source.manual": "Ручная проверка",
    "history.source.active": "Активная вкладка",
    "settings.title": "Настройки",
    "settings.subtitle": "Управляйте поведением CorgPhish",
    "settings.options": "Опции защиты",
    "settings.language.title": "Язык интерфейса",
    "settings.language.desc": "Переключайте русский и английский языки.",
    "settings.theme.title": "Тема интерфейса",
    "settings.theme.desc": "Переключайте светлый и тёмный режимы.",
    "settings.autoCheck.title": "Автопроверка при открытии",
    "settings.autoCheck.desc": "Автоматически запускать анализ при появлении попапа.",
    "settings.alerts.title": "Уведомления о рисках",
    "settings.alerts.desc": "Показывать предупреждение при подозрительном сайте.",
    "settings.block.title": "Блокировка ввода",
    "settings.block.desc": "На подозрительных сайтах запретить ввод и загрузки.",
    "settings.notify.title": "Системные уведомления",
    "settings.notify.desc": "Показывать уведомление при подозрительном сайте.",
    "settings.retention.title": "Автоочистка истории",
    "settings.retention.desc": "Ограничивайте давность записей в истории проверок.",
    "settings.retention.never": "Не очищать",
    "settings.retention.days7": "7 дней",
    "settings.retention.days30": "30 дней",
    "settings.retention.days90": "90 дней",
    "settings.compact.title": "Компактный режим",
    "settings.compact.desc": "Меньше отступов и плотнее карточки.",
    "settings.status.default": "Изменения сохраняются автоматически.",
    "settings.status.saved": "Настройки сохранены.",
    "whitelist.title": "Ваш белый список",
    "whitelist.add": "Добавить",
    "whitelist.placeholder": "example.com",
    "whitelist.note": "Добавленные домены проверяются вместе с локальным списком trusted.json.",
    "whitelist.empty": "Белый список пуст.",
    "whitelist.status.invalid": "Введите корректный домен.",
    "whitelist.status.exists": "Домен уже в белом списке.",
    "whitelist.status.added": "Добавлен {domain}.",
    "whitelist.status.removed": "Удалён {domain}.",
    "alerts.untrusted": "CorgPhish предупреждает: сайт {domain} не найден в списке доверенных.",
    "errors.activeTab": "Невозможно получить ссылку активной вкладки.",
    "errors.loadTrusted": "Не удалось загрузить trusted.json.",
    "errors.invalidTrusted": "Файл trusted.json содержит неверный формат.",
    "errors.invalidDomain": "Некорректный домен или URL.",
    "errors.modelLoad": "Не удалось загрузить ML-модель."
  },
  en: {
    "main.subtitle": "Protection dashboard",
    "actions.refresh": "Rescan",
    "actions.settings": "Settings",
    "actions.history": "Scan history",
    "actions.back": "Back",
    "actions.whitelist.addQuick": "Add to whitelist",
    "status.domainLabel": "Domain",
    "status.sourceLabel": "Source",
    "status.sourceValue": "trusted.json + ML + whitelist",
    "status.sourceValue.ml": "ML model",
    "status.sourceValue.list": "Whitelist + trusted.json",
    "status.sourceValue.mlRisk": "ML model (high risk)",
    "status.lastCheck": "Last check:",
    "status.pending.badge": "Scanning...",
    "status.pending.title": "Analyzing active tab",
    "status.pending.hint": "Comparing the address against the trusted domain catalog.",
    "status.pending.risk": "waiting for data",
    "status.pending.recommendations.0": "Make sure the tab you want to check is active.",
    "status.pending.recommendations.1": "Give us a second to finish the analysis.",
    "status.trusted.badge": "Trusted site",
    "status.trusted.title": "Site {domain} is trusted",
    "status.trusted.hint": "The domain is present in the local trusted list.",
    "status.trusted.risk": "low risk",
    "status.trusted.recommendations.0": "Always double-check the address before entering data.",
    "status.trusted.recommendations.1": "Use a password manager and enable MFA.",
    "status.untrusted.badge": "Suspicious site",
    "status.untrusted.title": "Site {domain} is not in the catalog",
    "status.untrusted.hint": "It may be a new service or a phishing attempt.",
    "status.untrusted.risk": "high risk",
    "status.untrusted.recommendations.0": "Do not enter personal data until the site is verified.",
    "status.untrusted.recommendations.1": "Compare the address with the official domain.",
    "status.untrusted.recommendations.2": "Search for reviews or mentions of {domain} online.",
    "status.untrusted.spoofWarning": "Looks similar to {spoofTarget}. Possible spoofing.",
    "status.mlSafe.badge": "ML: low risk",
    "status.mlSafe.title": "ML thinks {domain} is safe",
    "status.mlSafe.hint": "Not in the list, but the model marked it as legitimate.",
    "status.mlSafe.risk": "low risk (ML)",
    "status.mlRisky.badge": "ML: risk",
    "status.mlRisky.title": "ML flags {domain}",
    "status.mlRisky.hint": "Domain is not listed and ML sees high phishing risk.",
    "status.mlRisky.risk": "high risk (ML)",
    "status.unsupported.badge": "Cannot scan",
    "status.unsupported.title": "Only HTTP/HTTPS sites are supported",
    "status.unsupported.hint": "Browser pages and local files are skipped.",
    "status.unsupported.risk": "not defined",
    "status.unsupported.recommendations.0": "Open the desired website in the browser and try again.",
    "status.unsupported.recommendations.1": "Close the popup and activate the needed tab.",
    "status.error.badge": "Scan error",
    "status.error.title": "Something went wrong",
    "status.error.hint": "We could not finish the scan. {error}",
    "status.error.risk": "unknown",
    "status.error.recommendations.0": "Reload the extension or refresh the page.",
    "status.error.recommendations.1": "Make sure the trusted.json file is valid.",
    "recommendations.title": "Recommendations",
    "recommendations.initial": "Keep the tab open so we can analyze it.",
    "recommendations.empty": "No recommendations available.",
    "quickActions.title": "Quick actions",
    "footer.note": "CorgPhish only scans HTTP/HTTPS sites and works locally.",
    "manual.title": "Check a domain manually",
    "manual.description": "Inspect any domain without visiting it. Handy for links from emails or chats.",
    "manual.action": "Check",
    "manual.placeholder": "example.com",
    "manual.hint.default": "Type a domain or full URL, e.g. https://bank.com.",
    "manual.hint.success": "Domain {domain} was inspected.",
    "manual.hint.invalid": "Enter a valid domain or URL.",
    "stats.title": "Overview",
    "stats.trusted": "Trusted",
    "stats.alerts": "Flagged",
    "stats.whitelist": "In whitelist",
    "history.title": "Scan history",
    "history.subtitle": "Latest results",
    "history.sectionTitle": "Recent scans",
    "history.empty": "No scans yet. Please run a check.",
    "history.clear": "Clear",
    "history.note": "Up to 50 scans are stored locally.",
    "history.badge.trusted": "Trusted",
    "history.badge.alert": "Alert",
    "history.source.manual": "Manual check",
    "history.source.active": "Active tab",
    "settings.title": "Settings",
    "settings.subtitle": "Control CorgPhish behaviour",
    "settings.options": "Protection options",
    "settings.language.title": "Interface language",
    "settings.language.desc": "Switch between Russian and English.",
    "settings.theme.title": "Interface theme",
    "settings.theme.desc": "Toggle light and dark modes.",
    "settings.autoCheck.title": "Auto scan on open",
    "settings.autoCheck.desc": "Launch the analysis when the popup appears.",
    "settings.alerts.title": "Risk alerts",
    "settings.alerts.desc": "Show a warning when a suspicious site is detected.",
    "settings.block.title": "Block input",
    "settings.block.desc": "Block forms/downloads on suspicious sites.",
    "settings.notify.title": "System notifications",
    "settings.notify.desc": "Show a system notification on suspicious sites.",
    "settings.retention.title": "History cleanup",
    "settings.retention.desc": "Limit how long scan records are kept.",
    "settings.retention.never": "Never",
    "settings.retention.days7": "7 days",
    "settings.retention.days30": "30 days",
    "settings.retention.days90": "90 days",
    "settings.compact.title": "Compact mode",
    "settings.compact.desc": "Tighter spacing and condensed cards.",
    "settings.status.default": "Changes are saved automatically.",
    "settings.status.saved": "Settings saved.",
    "whitelist.title": "Your whitelist",
    "whitelist.add": "Add",
    "whitelist.placeholder": "example.com",
    "whitelist.note": "Added domains are checked together with trusted.json.",
    "whitelist.empty": "Whitelist is empty.",
    "whitelist.status.invalid": "Enter a valid domain.",
    "whitelist.status.exists": "The domain is already on the whitelist.",
    "whitelist.status.added": "Added {domain}.",
    "whitelist.status.removed": "Removed {domain}.",
    "alerts.untrusted": "CorgPhish warns: {domain} is not in the trusted list.",
    "errors.activeTab": "Cannot read the active tab URL.",
    "errors.loadTrusted": "Failed to load trusted.json.",
    "errors.invalidTrusted": "trusted.json has an invalid format.",
    "errors.invalidDomain": "Invalid domain or URL.",
    "errors.modelLoad": "Failed to load ML model."
  }
};
