// RU: Центральный реестр DOM-элементов и безопасное навешивание событий.
// EN: Central registry of DOM elements and safe event binding.
export const dom = {
  app: document.getElementById("app"),
  viewMain: document.getElementById("viewMain"),
  viewHistory: document.getElementById("viewHistory"),
  viewSettings: document.getElementById("viewSettings"),
  settingsTabButtons: Array.from(document.querySelectorAll("[data-settings-tab]")),
  settingsPanels: Array.from(document.querySelectorAll("[data-settings-panel]")),
  statusBadge: document.getElementById("statusBadge"),
  statusTitle: document.getElementById("statusTitle"),
  statusHint: document.getElementById("statusHint"),
  statusBanner: document.getElementById("statusBanner"),
  domainValue: document.getElementById("domainValue"),
  sourceValue: document.getElementById("sourceValue"),
  mlScore: document.getElementById("mlScore"),
  checkedAt: document.getElementById("checkedAt"),
  reasonTraceList: document.getElementById("reasonTraceList"),
  reasonTraceEmpty: document.getElementById("reasonTraceEmpty"),
  recommendationsList: document.getElementById("recommendationsList"),
  riskLevel: document.getElementById("riskLevel"),
  riskTag: document.getElementById("riskTag"),
  refreshBtn: document.getElementById("refreshBtn"),
  checkAllBtn: document.getElementById("checkAllBtn"),
  openSettingsBtn: document.getElementById("openSettingsBtn"),
  openHistoryBtn: document.getElementById("openHistoryBtn"),
  closeHistoryBtn: document.getElementById("closeHistoryBtn"),
  closeSettingsBtn: document.getElementById("closeSettingsBtn"),
  historyList: document.getElementById("historyList"),
  historyEmpty: document.getElementById("historyEmpty"),
  historySearchInput: document.getElementById("historySearchInput"),
  historyFilterSelect: document.getElementById("historyFilterSelect"),
  clearHistoryBtn: document.getElementById("clearHistoryBtn"),
  autoCheckInput: document.getElementById("autoCheckInput"),
  alertInput: document.getElementById("alertInput"),
  linkHighlightToggle: document.getElementById("linkHighlightToggle"),
  antiScamToggle: document.getElementById("antiScamToggle"),
  themeToggle: document.getElementById("themeToggle"),
  languageSelect: document.getElementById("languageSelect"),
  strictModeToggle: document.getElementById("strictModeToggle"),
  blockInputToggle: document.getElementById("blockInputToggle"),
  systemNotifyToggle: document.getElementById("systemNotifyToggle"),
  historyRetentionSelect: document.getElementById("historyRetentionSelect"),
  compactModeToggle: document.getElementById("compactModeToggle"),
  settingsStatus: document.getElementById("settingsStatus"),
  whitelistForm: document.getElementById("whitelistForm"),
  whitelistInput: document.getElementById("whitelistInput"),
  whitelistList: document.getElementById("whitelistList"),
  quickAddBtn: document.getElementById("quickAddBtn"),
  blacklistBtn: document.getElementById("blacklistBtn"),
  reportPhishingBtn: document.getElementById("reportPhishingBtn"),
  officialSiteBtn: document.getElementById("officialSiteBtn"),
  blacklistForm: document.getElementById("blacklistForm"),
  blacklistInput: document.getElementById("blacklistInput"),
  blacklistList: document.getElementById("blacklistList"),
  manualForm: document.getElementById("manualForm"),
  manualInput: document.getElementById("manualInput"),
  manualHint: document.getElementById("manualHint"),
  statsTrusted: document.getElementById("statsTrusted"),
  statsAlert: document.getElementById("statsAlert"),
  statsWhitelist: document.getElementById("statsWhitelist")
};

export const safeAddEvent = (element, event, handler) => {
  if (!element) return;
  element.addEventListener(event, handler);
};
